# Site install.
site:
  title: 'site title'
  url: 'site url'

  # Admin user.
  admin_user:
    name: admin
    password: admin
    email: admin@example.com

  # Site languages.
  languages:

    deafult:
      name: English
      code: en_US

    list:
      - name: Hebrew
        code: he_IL

      - name: Arabic
        code: ar

      - name: 'French (France)'
        code: fr_FR
