# Site install.
title: 'site title'
url: 'site url'

# Admin user.
admin_user:
  name:
  password: admin
  email: admin@example.com

# Site languages.
default-language:
  name: English
  code: en_US

# All site languages.
languages:
  - name: Hebrew
    code: he_IL

  - name: Arabic
    code: ar

  - name: 'French (France)'
    code: fr_FR
